### ISSUE TITLE
Renaming imports for production

### ISSUE THREAD

**Issue by GabrielCW** [jschilli/ember-cli-bless#2]
When building for prod with ember-cli, css files are suffixed, and it breaks the imports, who are searching for the files without suffixes.

Any suggestions on how to work around that problem?

**Comment by jschilli** [comment]
suffixed as in fingerprinted? `outputFile1-DEADBEEF.css` or suffixed as in `origFile1.css`, `origFile2.css`

**Comment by GabrielCW** [comment]
Fingerprinted, yes. For instance, in dev environment, I would have `vendor-blessed1.css`, but in production, it would be named `vendor-blessed1-7816936bc289c68ee139d33d1fa7c891.css`.

The import still looks for `vendor-blessed1.css` though.

**Comment by jschilli** [comment]
Hmm,

I just checked my production builds with blessed files and both the sub-blessed files as well as the imports are being renamed.

I’m going to suspect the fingerprinting process rather than bless itself.

**Comment by GabrielCW** [comment]
Do you have any pointers on how to troubleshoot this? I'm using ember-cli 1.13.13 and here's my config:

```
    bless: {
      enabled: true,
      cacheBuster: true,
      compress: true,
      force: false,
      imports: true
      // log: true
    }
```

**Comment by jschilli** [comment]
I’m assuming that you’re using standard ember-cli fingerprinting e.g. broccoli-asset-rev and not some additional addon.

You can disable fingerprinting (to test the  theory) by following config on https://github.com/rickharrison/broccoli-asset-rev#ember-cli-addon-usage https://github.com/rickharrison/broccoli-asset-rev#ember-cli-addon-usage

My recollection is 

```
    fingerprint: { 
        enabled:false
    }
```

 does it.

**Comment by GabrielCW** [comment]
Right, that will work for my use case, at least as a temporary solution. Thank you!
